//@version=5
indicator("IT Foundation Indicator", overlay=true)

var color bearish = input(color.green)
var color bullish = input(color.red)

// Define the SMAs
sma20 = ta.ema(close, 20)
sma50 = ta.ema(close, 50)
sma200 = ta.ema(close, 200)

// Define the color conditions
color20 = sma20 > sma50 ? bearish :bullish
color50 = sma50 > sma200 ? bearish :bullish
color200 = sma200 > sma200[1] ? bearish :bullish // Comparing to its previous value for a trend

// Plot the SMAs
plot(sma20, title="SMA 20", color=color20, linewidth=2)
plot(sma50, title="SMA 50", color=color50, linewidth=2)
plot(sma200, title="SMA 200", color=color200, linewidth=2)
