//@version=5
indicator("Order", overlay=true)
var orderName = input.string(defval = "",title="Name")
default = -1

orderGroup="Order"
entry = input.float(defval=default, group=orderGroup, title="Entry Price")
stop = input.float(defval=default, group=orderGroup, title="Stop Loss")
take = input.float(defval=default, group=orderGroup, title="Take Profit")

entryColor = input.color(color.gray, title="Entry")
stopColor = input.color(color.maroon, title="Entry")
takeColor = input.color(color.aqua, title="Entry")

var line entryLine = na
if (na(entryLine))
    entryLine := line.new(x1=bar_index - 1, y1=entry, x2=bar_index, y2=entry, color=entryColor, width=1, style=line.style_dotted, extend=extend.both)
else
    line.set_xy1(entryLine, bar_index - 1, entry)
    line.set_xy2(entryLine, bar_index, entry)

var line stopLine = na
if (na(stopLine))
    stopLine := line.new(x1=bar_index - 1, y1=stop, x2=bar_index, y2=entry, color=stopColor, width=1, style=line.style_dotted, extend=extend.both)
else
    line.set_xy1(stopLine, bar_index - 1, stop)
    line.set_xy2(stopLine, bar_index, stop)

var line takeLine = na
if (na(takeLine))
    takeLine := line.new(x1=bar_index - 1, y1=take, x2=bar_index, y2=entry, color=takeColor, width=1, style=line.style_dotted, extend=extend.both)
else
    line.set_xy1(takeLine, bar_index - 1, take)
    line.set_xy2(takeLine, bar_index, take)
if barstate.islast
    labelOffset = input.int(3, title = "Label Offset")
    entryLabel = label.new(x=bar_index + labelOffset, y=entry, text=orderName + " Entry Price", color=color.gray, textcolor=color.gray, style=label.style_none)
    stopLabel  = label.new(x=bar_index + labelOffset, y=stop, text=orderName + " Stop Loss", color=color.maroon, textcolor=color.maroon, style=label.style_none)
    takeLabel  = label.new(x=bar_index + labelOffset, y=take, text=orderName + " Take Profit", color=color.teal, textcolor=color.teal, style=label.style_none)
